
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// DEPRECATED: Use the prisma.config.ts file in the root of the project
// import "dotenv/config";
// import { defineConfig, env } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   engine: "classic",
//   datasource: {
//     url: env("DATABASE_URL") ?? "file:./dev.db",
//   },
// });
