// Vercel serverless function handler
// Use compiled version to avoid path alias issues
// @ts-ignore - dist/server.js is generated by build
import app from '../dist/server.js';

export default app;

